### ISSUE TITLE
Number of records retrieved with batch_pubmed_download() don't match the site

### ISSUE THREAD

**Issue by JFormoso** [cran/easyPubMed#4]
Hi! I can't figure out what I am doing wrong. Pubmed shows 66 records and the df resulting from this code returns 27. I've tried altering the sintax of the string and I always get the same result. 
If anyone can point me in the right direction... Thanks!

busqueda <- '((inference) AND (verbal ability)) AND (comprehension)' 

output <- batch_pubmed_download(pubmed_query_string = busqueda, 
                                  dest_file_prefix = "NUBL_18_", 
                                  encoding = "ASCII")

archivo <- output[[1]]

base <- table_articles_byAuth(pubmed_data = archivo, 
                                   included_authors = "first", 
                                   max_chars = -1, 
                                   encoding = "ASCII")

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
